CompileMode="" # debug or release
# config of WireGuard, it should be generated by WireGuard install script
InterfacePrivateKey=""
PeerPublicKey=""
PeerPresharedKey=""
# LF related config
LfVpnIp=""
JumpServerIp=""
JumpServerPort=""
